bot:
  name: ODSN_Poker_bot
  token: 6018932157:AAE-vDGHZN8vcRiJFmwvZP-5XoJ0JBWzT4w
spring:
  datasource:
    #      url: jdbc:postgresql://ec2-54-75-199-252.eu-west-1.compute.amazonaws.com:5432/d5p9skg6nin3mh?user=bozuqwnhjhoubl&password=8a40050de8a0014c14df49aeaac5880f1ac633cc20c78a4cc3b32323231
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qazzaq
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
